import cookie from "@fastify/cookie";
import rateLimit from "@fastify/rate-limit";
import {
  scryptSync,
  timingSafeEqual
} from "node:crypto";
import type {
  FastifyInstance,
  FastifyReply,
  FastifyRequest
} from "fastify";
import { z } from "zod";

const SESSION_COOKIE = "deployment_platform_session";
const SESSION_DURATION_SECONDS = 60 * 60 * 8;

const loginSchema = z.object({
  username: z.string().min(1).max(100),
  password: z.string().min(1).max(500)
});

interface SessionData {
  username: string;
  expiresAt: number;
}

function getRequiredEnvironmentVariable(name: string): string {
  const value = process.env[name];

  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }

  return value;
}

// The canonical ADMIN_PASSWORD_HASH format, fixed by
// installer/lib/secrets.sh (compute_password_hash):
//   randomBytes(32) salt, scryptSync(password, salt, 64) derived key,
//   both lowercase hex, joined by a single colon.
// These are the authority on the required shape — deliberately NOT the
// stored value's own length. See verifyPassword for why that matters.
const PASSWORD_HASH_SALT_BYTES = 32;
const PASSWORD_HASH_KEY_BYTES = 64;
const PASSWORD_HASH_SALT_HEX_LENGTH = PASSWORD_HASH_SALT_BYTES * 2;
const PASSWORD_HASH_KEY_HEX_LENGTH = PASSWORD_HASH_KEY_BYTES * 2;

// Lowercase hex only. Combined with the exact length checks below this
// also rules out uppercase hex, non-hex characters, and odd-length hex
// (both canonical lengths are even, so any odd length fails outright).
const LOWERCASE_HEX_PATTERN = /^[0-9a-f]+$/;

interface ParsedPasswordHash {
  salt: Buffer;
  expectedHash: Buffer;
}

/**
 * Strictly validates the canonical format and returns null for anything
 * else — never throws, so login verification can treat a malformed
 * stored hash as simply "does not match" rather than crashing a request.
 */
function tryParsePasswordHash(value: string): ParsedPasswordHash | null {
  if (value.length === 0) {
    return null;
  }

  // No leading or trailing whitespace tolerated: a stray newline in the
  // env file must not silently change what is being validated.
  if (value !== value.trim()) {
    return null;
  }

  // Exactly one separator: catches both a missing colon and any extra.
  const parts = value.split(":");

  if (parts.length !== 2) {
    return null;
  }

  const [saltHex, hashHex] = parts;

  if (
    saltHex.length !== PASSWORD_HASH_SALT_HEX_LENGTH ||
    hashHex.length !== PASSWORD_HASH_KEY_HEX_LENGTH
  ) {
    return null;
  }

  if (
    !LOWERCASE_HEX_PATTERN.test(saltHex) ||
    !LOWERCASE_HEX_PATTERN.test(hashHex)
  ) {
    return null;
  }

  const salt = Buffer.from(saltHex, "hex");
  const expectedHash = Buffer.from(hashHex, "hex");

  // Belt and braces: the decoded byte lengths must also be canonical.
  if (
    salt.length !== PASSWORD_HASH_SALT_BYTES ||
    expectedHash.length !== PASSWORD_HASH_KEY_BYTES
  ) {
    return null;
  }

  return {
    salt,
    expectedHash
  };
}

/**
 * Throwing wrapper used once at startup so a misconfigured server fails
 * fast with a clear message instead of rejecting every login at runtime.
 * The message describes the required shape only — never the value.
 */
function parsePasswordHash(value: string): ParsedPasswordHash {
  const parsed = tryParsePasswordHash(value);

  if (!parsed) {
    throw new Error(
      `ADMIN_PASSWORD_HASH must be <${PASSWORD_HASH_SALT_HEX_LENGTH} lowercase hex characters>:<${PASSWORD_HASH_KEY_HEX_LENGTH} lowercase hex characters> ` +
        `(a ${PASSWORD_HASH_SALT_BYTES}-byte salt and a ${PASSWORD_HASH_KEY_BYTES}-byte scrypt key, as generated by the installer)`
    );
  }

  return parsed;
}

// Exported for the installer/API password-hash contract test
// (tests/password-hash-contract.test.ts). The installer computes
// ADMIN_PASSWORD_HASH in a sandboxed Node helper container; this is the
// verifier that must accept it. Exporting the real function means the
// test exercises production verification logic rather than a copy of it.
export function verifyPassword(
  password: string,
  passwordHash: string
): boolean {
  const parsed = tryParsePasswordHash(passwordHash);

  // A stored hash that is not in canonical form can never match.
  if (!parsed) {
    return false;
  }

  const { salt, expectedHash } = parsed;

  // The derived length comes from the canonical constant, NEVER from
  // expectedHash.length. Deriving from the stored value's length made
  // the stored value the authority on the required format: truncating
  // ADMIN_PASSWORD_HASH to 32 bytes shortened the derivation to 32
  // bytes too, so the truncated hash still verified — a corrupted or
  // tampered config could weaken scrypt's output without detection.
  const suppliedHash = scryptSync(
    password,
    salt,
    PASSWORD_HASH_KEY_BYTES
  );

  // timingSafeEqual throws on length mismatch, so both buffers are
  // confirmed to be exactly the canonical length before comparing.
  if (
    suppliedHash.length !== PASSWORD_HASH_KEY_BYTES ||
    expectedHash.length !== PASSWORD_HASH_KEY_BYTES
  ) {
    return false;
  }

  return timingSafeEqual(suppliedHash, expectedHash);
}

function encodeSession(session: SessionData): string {
  return Buffer.from(
    JSON.stringify(session),
    "utf8"
  ).toString("base64url");
}

function decodeSession(value: string): SessionData | null {
  try {
    const parsed = JSON.parse(
      Buffer.from(value, "base64url").toString("utf8")
    ) as Partial<SessionData>;

    if (
      typeof parsed.username !== "string" ||
      typeof parsed.expiresAt !== "number"
    ) {
      return null;
    }

    return {
      username: parsed.username,
      expiresAt: parsed.expiresAt
    };
  } catch {
    return null;
  }
}

function clearSessionCookie(reply: FastifyReply): void {
  reply.clearCookie(SESSION_COOKIE, {
    path: "/"
  });
}

export async function registerAuthentication(
  app: FastifyInstance
): Promise<void> {
  const adminUsername =
    getRequiredEnvironmentVariable("ADMIN_USERNAME");

  const adminPasswordHash =
    getRequiredEnvironmentVariable("ADMIN_PASSWORD_HASH");

  const sessionSecret =
    getRequiredEnvironmentVariable("SESSION_SECRET");

  const cookieSecure =
    process.env.COOKIE_SECURE?.toLowerCase() === "true";

  parsePasswordHash(adminPasswordHash);

  await app.register(cookie, {
    secret: sessionSecret,
    hook: "onRequest"
  });

  await app.register(rateLimit, {
    global: false
  });

  function readSession(
    request: FastifyRequest
  ): SessionData | null {
    const signedCookie = request.cookies[SESSION_COOKIE];

    if (!signedCookie) {
      return null;
    }

    const unsigned = request.unsignCookie(signedCookie);

    if (!unsigned.valid || !unsigned.value) {
      return null;
    }

    const session = decodeSession(unsigned.value);

    if (!session) {
      return null;
    }

    if (session.expiresAt <= Date.now()) {
      return null;
    }

    if (session.username !== adminUsername) {
      return null;
    }

    return session;
  }

  app.post(
    "/auth/login",
    {
      config: {
        rateLimit: {
          max: 5,
          timeWindow: "1 minute"
        }
      }
    },
    async (request, reply) => {
      const parsedBody = loginSchema.safeParse(request.body);

      if (!parsedBody.success) {
        return reply.code(400).send({
          success: false,
          message: "Username and password are required"
        });
      }

      const usernameMatches =
        parsedBody.data.username === adminUsername;

      const passwordMatches = verifyPassword(
        parsedBody.data.password,
        adminPasswordHash
      );

      if (!usernameMatches || !passwordMatches) {
        return reply.code(401).send({
          success: false,
          message: "Invalid username or password"
        });
      }

      const session: SessionData = {
        username: adminUsername,
        expiresAt:
          Date.now() + SESSION_DURATION_SECONDS * 1000
      };

      reply.setCookie(
        SESSION_COOKIE,
        encodeSession(session),
        {
          path: "/",
          httpOnly: true,
          sameSite: "strict",
          secure: cookieSecure,
          signed: true,
          maxAge: SESSION_DURATION_SECONDS
        }
      );

      return {
        success: true,
        username: adminUsername,
        expiresAt: session.expiresAt
      };
    }
  );

  app.get("/auth/session", async (request) => {
    const session = readSession(request);

    if (!session) {
      return {
        authenticated: false
      };
    }

    return {
      authenticated: true,
      username: session.username,
      expiresAt: session.expiresAt
    };
  });

  app.addHook("onRequest", async (request, reply) => {
    const pathname = request.url.split("?")[0];

    const publicPaths = new Set([
      "/",
      "/health",
      "/auth/login",
      "/auth/session"
    ]);

    if (publicPaths.has(pathname)) {
      return;
    }

    const session = readSession(request);

    if (!session) {
      clearSessionCookie(reply);

      return reply.code(401).send({
        success: false,
        message: "Authentication required"
      });
    }
  });

  app.post("/auth/logout", async (_request, reply) => {
    clearSessionCookie(reply);

    return {
      success: true,
      message: "Logged out"
    };
  });
}
